name: finemapping
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.18.0=h4e3cde8_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=hc5723f1_16
  - gfortran_impl_linux-64=15.2.0=h281d09f_16
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=hda75c37_16
  - harfbuzz=12.2.0=h15599e2_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.53=h421ea60_0
  - libsanitizer=15.2.0=h90f66d4_16
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.10.19=h3c07f61_2_cpython
  - r-argparse=2.3.1=r45hc72bb7e_0
  - r-base=4.5.2=h835929b_3
  - r-cli=3.6.5=r45h3697838_1
  - r-colorspace=2.1_2=r45h54b55ab_0
  - r-cpp11=0.5.2=r45h785f33e_2
  - r-crayon=1.5.3=r45hc72bb7e_2
  - r-farver=2.1.2=r45h3697838_2
  - r-findpython=1.0.9=r45hc72bb7e_1
  - r-ggplot2=4.0.1=r45h785f33e_0
  - r-glue=1.8.0=r45h54b55ab_1
  - r-gtable=0.3.6=r45hc72bb7e_1
  - r-irlba=2.3.5.1=r45h0e4624f_4
  - r-isoband=0.3.0=r45h3697838_0
  - r-jsonlite=2.0.0=r45h54b55ab_1
  - r-labeling=0.4.3=r45hc72bb7e_2
  - r-lattice=0.22_7=r45h54b55ab_1
  - r-lifecycle=1.0.5=r45hc72bb7e_0
  - r-matrix=1.7_4=r45h0e4624f_1
  - r-matrixstats=1.5.0=r45h54b55ab_1
  - r-mixsqp=0.3_54=r45h3704496_4
  - r-munsell=0.5.1=r45hc72bb7e_2
  - r-plyr=1.8.9=r45h3697838_3
  - r-r6=2.6.1=r45hc72bb7e_1
  - r-rcolorbrewer=1.1_3=r45h785f33e_4
  - r-rcpp=1.1.1=r45h3697838_0
  - r-rcpparmadillo=15.2.3_1=r45h3704496_0
  - r-reshape=0.8.10=r45hc72bb7e_1
  - r-rlang=1.1.7=r45h3697838_0
  - r-s7=0.2.1=r45h54b55ab_0
  - r-scales=1.4.0=r45hc72bb7e_1
  - r-susier=0.14.2=r45hc72bb7e_1
  - r-vctrs=0.6.5=r45h3697838_2
  - r-viridislite=0.4.2=r45hc72bb7e_3
  - r-withr=3.0.2=r45hc72bb7e_1
  - readline=8.3=h853b02a_0
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tk=8.6.13=noxft_ha0e22de_103
  - tktable=2.10=h8d826fa_7
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiodns==2.0.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - argparse==1.4.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - avro==1.11.5
      - azure-common==1.1.28
      - azure-core==1.37.0
      - azure-identity==1.25.1
      - azure-mgmt-core==1.6.0
      - azure-mgmt-storage==20.1.0
      - azure-storage-blob==12.27.1
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - bokeh==3.4.3
      - boto3==1.42.22
      - botocore==1.42.22
      - cachetools==6.2.4
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - comm==0.2.3
      - commonmark==0.9.1
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==4.4.2
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.4.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.61.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - google-auth==2.46.0
      - google-auth-oauthlib==0.8.0
      - h11==0.16.0
      - hail==0.2.137
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanize==4.15.0
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - isodate==0.7.2
      - isoduration==20.11.0
      - janus==1.0.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jproperties==2.1.2
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.7.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - msrest==0.7.1
      - multidict==6.7.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.5.1
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - oauthlib==3.3.1
      - orjson==3.11.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parsimonious==0.11.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - plotly==5.24.1
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py4j==0.10.9.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycares==5.0.1
      - pycparser==2.23
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyparsing==3.3.1
      - pyspark==3.5.7
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==12.6.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - s3fs==2025.12.0
      - s3transfer==0.16.0
      - scipy==1.15.3
      - send2trash==2.0.0
      - shellingham==1.5.4
      - six==1.17.0
      - sortedcontainers==2.4.0
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - typer==0.21.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - ukbb-common==0.1.2
      - uri-template==1.3.0
      - urllib3==2.6.2
      - uvloop==0.21.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - xyzservices==2025.11.0
      - yarl==1.22.0
prefix: /home/tobyc/data/miniforge3/envs/finemapping
